//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeExplorers.Wheels.AppServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Balance { get; set; }
        public string Supplier { get; set; }
        public bool IsEffective { get; set; }
        public System.DateTime BegineEffective { get; set; }
        public System.DateTime EndEffective { get; set; }
    }
}
